### ISSUE TITLE
Time to archive the project?

### ISSUE THREAD

**Issue by talentlessguy** [henriquehbr/eswatch#6]
esbuild 0.11 has a `--watch` flag so probably eswatch is not needed anymore.

example:

```sh
esbuild --watch ./index.ts 
```

**Comment by henriquehbr** [comment]
Wasn't this flag released in [`0.8.38`](https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#0838)?

Anyways, seems pretty reasonable to me, as i couldn't find enough time to work on this, besides that, there's also a bunch of other similar projects that offer a wider range of features and performs better, and also, the code is kinda messy, more than i care to admit and maintain

At the moment, i'm a bit out of the loop in regards to esbuild latest updates, but i'll take a moment to read the changelog, see what changed, and almost surely, put this repo on the shelf

Thanks for your suggestion!

**Comment by talentlessguy** [comment]
@henriquehbr yeah my bad, I just was checking locally while having esbuild 0.10 but yup it was added in 0.8.38

**Comment by henriquehbr** [comment]
As i'm not willing to keep maintaining this project anymore due to a number of reasons (including the ones previously mentioned), i consider as valid the decision of archiving the project, a final [release](https://github.com/henriquehbr/eswatch/compare/v1.0.0-alpha.2...v1.0.0) containing unreleased changes has just been made

Thanks for the heads up @talentlessguy!
